site_name: ManaTEE
site_url: https://manatee-project.github.io
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate
  logo: assets/img/manatee.png
  palette:
    scheme: manatee
repo_url: https://github.com/manatee-project/manatee
repo_name: manatee-project/manatee

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manatee-project/manatee

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Introduction: index.md
  - Project Status: project-status.md
  - Getting Started:
    - Build: getting-started/building.md
    - Deploy:
        - GCP: getting-started/deployment.md
  - Tutorials: getting-started/tutorials.md
  - Developer:
    - developer/architecture.md
