// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/manatee-project/manatee/app/api/biz/dal"
)

func Init() {
	dal.Init()
}

func main() {
	Init()
	h := server.Default(server.WithHostPorts(":8080"), server.WithMaxRequestBodySize(6*1024*1024*1024))

	register(h)
	h.Spin()
}
