# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: manatee-configmap
data:
  env: {{ .Values.config.env | quote }}
  project_id: {{ .Values.config.project_id | quote }}
  zone: {{ .Values.config.zone | quote }}
  region: {{ .Values.config.region | quote }}
  debug: {{ .Values.config.debug | quote }}