apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-monitor" (include "data-clean-room-chart.fullname" .) | quote }}
  labels:
    {{- include "data-clean-room-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "data-clean-room-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "data-clean-room-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "data-clean-room-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: "Always"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.monitorImage.repository }}:{{ .Values.monitorImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.monitorImage.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATA_CLEAN_ROOM_HOST
              value: {{ printf "http://%s.%s.svc.cluster.local" (include "data-clean-room-chart.fullname" .) .Values.namespace | quote }}
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PORT
              value:  {{ .Values.mysql.port | quote }}
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: env
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: projectId
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: region
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: zone
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: debug
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: storageType
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: minioEndpoint
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: minioAccessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: manatee-configmap
                  key: minioSecretKey
            - name: REGISTRY_TYPE
              valueFrom:
                  configMapKeyRef:
                    name: manatee-configmap
                    key: registryType
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--structured-logs"
            - "--private-ip"
            - {{ print "--port=" .Values.mysql.port }}
            - {{ .Values.cloudSql.connection_name }}
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}