on:
  pull_request:
    branches: [main]
jobs:
  format:
    name: Enforce Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Check code format
        run: |
          bazelisk run @go_sdk//:bin/gofmt -- -l . > gofmt_output.txt || true
          if [ -s gofmt_output.txt ]; then
            echo "Following files are not properly formatted:"
            cat gofmt_output.txt
            echo "Please run: bazelisk run @go_sdk//:bin/gofmt -- -w ."
            exit 1
          else
            echo "All files are properly formatted!"
          fi

